Vm remove fails due to spelling mistake
Vm remove fails with:

[NameError]: undefined local variable or method `exception' for
 #<OvirtSDK4::VmService:0x0000000013977620>  Method:[block in method_missing]

This patch fixes the issue.

Bug-Url: https://bugzilla.redhat.com/1509020
Change-Id: I622cb7f3b39a19314b7de4c325a62fa47faeaa4d
Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>